### PR TITLE
refactor: add region to AI

### PR DESCRIPTION
**Pull request by JonathanStarup**
It's a bit, uhmm, interesting. To make you feel convinced, first look at how natural the stateful AI's now are to implement. Then you can look at the weird code that makes it work 😄

Related to #40

### CODE REVIEW

**Comment by mlutze** [comment]
I have some reservations about this, especially making GameState impure.

I'd be more comfortable with something like the following:
- Functions that convert `AiState -> MutableX`
- Functions that convert `MutableX -> AiState`
- Maybe make that into a type class

It would require a little more engineering, but afterward we can use whichever style we want to write the AIs.

I'm particularly interested in keeping GameState pure because it allows for serialization. We can easily write it to a file and then load a Game from a certain point. If additional state is hidden behind functions, we can no longer do that.

**Comment by JonathanStarup** [comment]
can you elaborate on AiState and MutableX?

**Comment by mlutze** [comment]
Here's an example.

```scala
def stateToBool(r: Region[r], state: AiState): Ref[r, Bool] = {
    let (i, _) = state;
    ref (i % 2 == 0)
}

def boolToState(r: Ref[r, Bool]): AiState = {
    if (deref r) {
        (0, Map.empty())
    } else {
        (1, Map.empty())
    }
}

type alias StatefulMoveLogic[r: Region, state: Type] = (GameState, Id, state) -> Move \ r

def wiggle(): StatefulMoveLogic[r, Ref[r, Bool]] = {
    (_gs, _id, state) -> if (deref state) {
        state := false;
        Turn(Clockwise)
    } else {
        state := true;
        Turn(Counterclockwise)
    }
}

def mkMoveLogic(m: StatefulMoveLogic[r, Ref[r, Bool]]): MoveLogic = {
    (gs, id, aiState) ->
        let state = stateToBool(aiState);
        let move = m(gs, id, state);
        let newAiState = boolToState(state);
        (move, newAiState)
}
```

The `mkMoveLogic` I think can be generalized to use a type class.

**Comment by JonathanStarup** [comment]
Aah, very cool! Materializing the state between moves to remove the effect. The stateToBool and BoolToState could be type classes right? this also allows whatever state rep we want while ai functions could somewhat be oblivious if the stick to compositions of implemented instances (with a composer function of state translations)

You've convinced me 👍 (although I still wish we had existential types)

**Comment by JonathanStarup** [comment]
In conclusion: Avoid state in the gamestate for serialization, AI state can be faked by encoding/decoding between flix state state and data state

**Pull request closed without merging**
