### PR TITLE
refactor: use JonathanStarup/Flix-ANSI-Terminal pkg

### LINKED ISSUE #41: Factor out ANSI stuff
And just depend on https://github.com/JonathanStarup/Flix-ANSI-Terminal

### PR DESCRIPTION
**Pull request by JonathanStarup**
use [JonathanStarup/Flix-ANSI-Terminal](https://github.com/JonathanStarup/Flix-ANSI-Terminal) for terminal manipulation.
Fixes #41.

### CODE REVIEW

**Comment by JonathanStarup** [comment]
@mlutze you can merge if you agree with the readme layout

**Comment by mlutze** [comment]
The quick fix is to add `flix install JonathanStarup/Flix-ANSI-Terminal` to each of the build scripts.
Or we could try something a bit more advanced like having a text file listing the dependencies and running `install` for each, but that seems like it could quickly get messy.

**Comment by JonathanStarup** [comment]
> The quick fix is to add `flix install JonathanStarup/Flix-ANSI-Terminal` to each of the build scripts. Or we could try something a bit more advanced like having a text file listing the dependencies and running `install` for each, but that seems like it could quickly get messy.

Hmm yeah. Is there a way to give the build system a set of files not contained in the repo? I guess that we're waiting for a proper system so for now we just need it to work so lets just take the easiest option. I've not used these actions before, can you add the flix install command?

**Comment by mlutze** [comment]
I've added the commands to the build scripts.

**Pull request merged**
