### PR TITLE
refactor: change AiState to shaped enum

### LINKED ISSUE #57: The shape of AiState
`AiState`'s definition is this:

```scala
pub type alias AiState = (Int32, Map[String, String])
```
where the `Int32` part is for easy counting, etc. and the `Map` part is for arbitrary storage.

It's kind of weird to have a "int part" and "everything else part".

I propose instead the following:
```scala
pub enum AiState {
    case Value(String)
    case Collection(List[AiState])
}
```

This makes it a simple enum and conversions to most types come quite naturally. I was originally considering a JSON style but all the types add unnecessary complexity. We lose some guarantees in the conversion for integers, due to malformed encoding, but that was always going to be a potential issue with anything nontrivial anyway, so I don't have a problem with just falling back to some default value in this case.

Serialization of this is also very easy, as we can just do, e.g. a Lisp Syntax.

### PR DESCRIPTION
**Pull request by mlutze**
Step 1 for the Stateable type class

fixes #57

### CODE REVIEW

**Comment by mlutze** [comment]
Looks like we now have to choose between nightly and master. @JonathanStarup any preference?

**Comment by JonathanStarup** [comment]
> Looks like we now have to choose between nightly and master. @JonathanStarup any preference?

long term i think it should be stable release but master seems fine for now

**Comment by mlutze** [comment]
The other question is what to do with malformed AiState.
The options are:
1. return an option
2. crash the program
3. use some default value

I did 3 here, but I'm not sure whether that's the best choice.

**Comment by JonathanStarup** [comment]
> The other question is what to do with malformed AiState.
> The options are:
> 1. return an option
> 2. crash the program
> 3. use some default value
> 
> I did 3 here, but I'm not sure whether that's the best choice.

I think we should return a result, but also try-catch around the function in the engine. I think it's sensible, and better for bug catching to avoid defaults.

**Comment by mlutze** [comment]
> I assume that the AI defines an initial state right? so i think if we want to later, we could have the engine reset the state to the initial one on parsing errors. this way we know that its a valid state

Good point

**Pull request merged**
